algoritmo "Final_De_Semana"
// Função :
// Autor(a): Danilo Ramos
// Data : 02/09/2015
// Seção de Declarações 
var
   opcao : inteiro
inicio
// Seção de Comandos
   escreval("Escola a opção abaixo: ")
   escreval(" [1] Maçâ")
   escreval(" [2] Banana")
   escreval(" [3] Abacaxi")
   escreval("")
   escreval("Qual fruta? ")
   leia(opcao)
   
   escolha (opcao)
   caso 1
        escreval("Você gosta de Maçâ")
   caso 2
        escreval("Voce gosta de Banana")
   caso 3
        escreval("Você gosta de Abacaxi")
   outrocaso
        escreval("Voce não gosta de fruta!")
   fimescolha
   
fimalgoritmo
