algoritmo "semnome"
// Função :
// Autor(a): Danilo Ramos
// Data : 11/09/2015
// Seção de Declarações 
var

inicio
// Seção de Comandos

   escreval("Sua média foi ",media_aluno1:4:2)

   se(media_aluno1 >= 7) entao
           escreval("Aluno APROVADO")
      senao
              se(media_aluno1 >=5) e (media_aluno1 < 7) entao
                   escreval("Aluno em RECUPERAÇÂO")
              senao
                   escreval("Aluno REPROVADO")
              fimse
   fimse
   


       escreval("Sua média foi ",media_aluno2:4:2)

   se(media_aluno2 >= 7) entao
           escreval("Aluno APROVADO")
      senao
              se(media_aluno2 >=5) e (media_aluno2 < 7) entao
                   escreval("Aluno em RECUPERAÇÂO")
              senao
                   escreval("Aluno REPROVADO")
              fimse
   fimse
   

       escreval("Sua média foi ",media_aluno3:4:2)

   se(media_aluno3 >= 7) entao
           escreval("Aluno APROVADO")
      senao
              se(media_aluno3 >=5) e (media_aluno3 < 7) entao
                   escreval("Aluno em RECUPERAÇÂO")
              senao
                   escreval("Aluno REPROVADO")
              fimse
   fimse
   
   escreval("Sua média foi ",media_aluno4:4:2)

   se(media_aluno4 >= 7) entao
           escreval("Aluno APROVADO")
      senao
              se(media_aluno4 >=5) e (media_aluno4 < 7) entao
                   escreval("Aluno em RECUPERAÇÂO")
              senao
                   escreval("Aluno REPROVADO")
              fimse
   fimse
   

       escreval("Sua média foi ",media_aluno5:4:2)

    se(media_aluno5 >= 7) entao
           escreval("Aluno APROVADO")
      senao
              se(media_aluno5 >=5) e (media_aluno5 < 7) entao
                   escreval("Aluno em RECUPERAÇÂO")
              senao
                   escreval("Aluno REPROVADO")
              fimse
   fimse
 
fimalgoritmo
